# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-11 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incubator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incubator',
            options={'verbose_name': '孵化器', 'verbose_name_plural': '孵化器'},
        ),
    ]
