# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-10 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverrequest',
            name='img',
            field=models.ImageField(default=False, upload_to='static/img/'),
        ),
    ]
