# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-11 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='independentevaluationofenterprises',
            options={'verbose_name': '自主评价', 'verbose_name_plural': '自主评价'},
        ),
        migrations.AddField(
            model_name='evaluationofenterprises',
            name='companyInfo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.CompanyInfo', verbose_name='企业'),
        ),
        migrations.AddField(
            model_name='independentevaluationofenterprises',
            name='companyInfo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.CompanyInfo', verbose_name='企业'),
        ),
        migrations.AlterField(
            model_name='independentevaluationofenterprises',
            name='external_environment',
            field=models.SmallIntegerField(blank=True, choices=[(1, '1分'), (2, '2分'), (3, '3分'), (4, '4分'), (5, '5分'), (6, '6分'), (7, '7分'), (8, '8分'), (9, '9分'), (10, '10分')], null=True, verbose_name='企业所处外部环境（权重：2）'),
        ),
        migrations.AlterField(
            model_name='independentevaluationofenterprises',
            name='products_and_market',
            field=models.SmallIntegerField(blank=True, choices=[(1, '1分'), (2, '2分'), (3, '3分'), (4, '4分'), (5, '5分'), (6, '6分'), (7, '7分'), (8, '8分'), (9, '9分'), (10, '10分')], null=True, verbose_name='企业主营产品及市场开拓（权重：2）'),
        ),
        migrations.AlterField(
            model_name='independentevaluationofenterprises',
            name='team',
            field=models.SmallIntegerField(blank=True, choices=[(1, '1分'), (2, '2分'), (3, '3分'), (4, '4分'), (5, '5分'), (6, '6分'), (7, '7分'), (8, '8分'), (9, '9分'), (10, '10分')], null=True, verbose_name='企业经营及管理团队（权重：4）'),
        ),
        migrations.AlterField(
            model_name='independentevaluationofenterprises',
            name='technology_R_D',
            field=models.SmallIntegerField(blank=True, choices=[(1, '1分'), (2, '2分'), (3, '3分'), (4, '4分'), (5, '5分'), (6, '6分'), (7, '7分'), (8, '8分'), (9, '9分'), (10, '10分')], null=True, verbose_name='企业核心技术及研发实力（权重：2）'),
        ),
    ]
