# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-10 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_serverrequest_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverrequest',
            name='img',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='business_license_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/upload/company'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='credit_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='统一社会信用代码'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='企业手机'),
        ),
    ]
