# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-28 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='is_high_tech_enterprise',
            field=models.BooleanField(default=False, verbose_name='是否是高新技术企业'),
        ),
        migrations.AlterField(
            model_name='coremember',
            name='is_study_abroad',
            field=models.BooleanField(default=False, verbose_name='留学经历'),
        ),
    ]
