# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-29 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180928_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(verbose_name='年份')),
                ('name', models.CharField(max_length=2)),
                ('value', models.FloatField()),
                ('companyInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.CompanyInfo', verbose_name='企业')),
            ],
        ),
        migrations.AlterModelOptions(
            name='coremember',
            options={'verbose_name': '\u2003\u2003核心团队(至少三人)', 'verbose_name_plural': '\u2003\u2003核心团队(至少三人)'},
        ),
        migrations.AlterField(
            model_name='financialsituation',
            name='companyInfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.CompanyInfo', verbose_name='企业'),
        ),
    ]
