# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-08 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180929_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='companyInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.CompanyInfo', verbose_name='企业'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='name',
            field=models.CharField(max_length=4),
        ),
    ]
