# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-09 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20181008_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(verbose_name='年份')),
                ('name', models.CharField(max_length=4)),
                ('value', models.FloatField()),
                ('companyInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.CompanyInfo', verbose_name='企业')),
            ],
        ),
    ]
