# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-17 03:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i0', models.BooleanField(choices=[(0, '0分'), (1, '5分')], default=False, verbose_name='应收账款周转率（5）')),
                ('i1', models.BooleanField(choices=[(0, '0分'), (1, '5分')], default=False, verbose_name='存货周转率（5）')),
                ('i2', models.BooleanField(choices=[(0, '0分'), (1, '5分')], default=False, verbose_name='总资产周转率（5）')),
                ('i3', models.BooleanField(choices=[(0, '0分'), (1, '10分')], default=False, verbose_name='净利润增长率（10）')),
                ('i4', models.BooleanField(choices=[(0, '0分'), (1, '5分')], default=False, verbose_name='净资产增长率（5）')),
                ('i5', models.BooleanField(choices=[(0, '0分'), (1, '5分')], default=False, verbose_name='销售收入增长率（5）')),
                ('i6', models.BooleanField(choices=[(0, '0分'), (1, '10分')], default=False, verbose_name='*净利润率（10）')),
                ('i7', models.BooleanField(choices=[(0, '0分'), (1, '5分')], default=False, verbose_name='总资产报酬率（5）')),
                ('i8', models.BooleanField(choices=[(0, '0分'), (1, '5分')], default=False, verbose_name='*净资产收益率（5）')),
                ('i9', models.BooleanField(choices=[(0, '0分'), (1, '10分')], default=False, verbose_name='*资产负债率（10）')),
                ('i10', models.BooleanField(choices=[(0, '0分'), (1, '10分')], default=False, verbose_name='*经营现金流量负债比（10）')),
                ('i11', models.BooleanField(choices=[(0, '0分'), (1, '7分')], default=False, verbose_name='*流动比率（7）')),
                ('i12', models.BooleanField(choices=[(0, '0分'), (1, '8分')], default=False, verbose_name='*利息保障倍数（8）')),
                ('i13', models.BooleanField(choices=[(0, '0分'), (1, '10分')], default=False, verbose_name='研发费用收入比例(10)')),
                ('create_date', models.DateTimeField(auto_now=True, null=True, verbose_name='生成时间')),
                ('companyInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyInfo', verbose_name='企业')),
            ],
            options={
                'verbose_name': '银行类金融报告',
                'verbose_name_plural': '银行类金融报告',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(blank=True, choices=[(1, '投资'), (2, '银行')], null=True, verbose_name='机构类型')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='机构名称')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='联系电话')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '机构',
                'verbose_name_plural': '机构',
            },
        ),
        migrations.CreateModel(
            name='InvestReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i5', models.BooleanField(choices=[(0, '0分'), (1, '10分')], default=False, verbose_name='应收账款周转率（10）')),
                ('i6', models.BooleanField(choices=[(0, '0分'), (1, '7分')], default=False, verbose_name='存货周转率（7）')),
                ('i7', models.BooleanField(choices=[(0, '0分'), (1, '8分')], default=False, verbose_name='总资产周转率（8）')),
                ('i8', models.BooleanField(choices=[(0, '0分'), (1, '10分')], default=False, verbose_name='净利润增长率（10）')),
                ('i9', models.BooleanField(choices=[(0, '0分'), (1, '5分')], default=False, verbose_name='净资产增长率（5）')),
                ('i10', models.BooleanField(choices=[(0, '0分'), (1, '10分')], default=False, verbose_name='销售收入增长率（10）')),
                ('i11', models.BooleanField(choices=[(0, '0分'), (1, '10分')], default=False, verbose_name='*净利润率（10）')),
                ('i12', models.BooleanField(choices=[(0, '0分'), (1, '5分')], default=False, verbose_name='总资产报酬率（5）')),
                ('i13', models.BooleanField(choices=[(0, '0分'), (1, '5分')], default=False, verbose_name='*净资产收益率（5）')),
                ('i14', models.BooleanField(choices=[(0, '0分'), (1, '5分')], default=False, verbose_name='*资产负债率（5）')),
                ('i15', models.BooleanField(choices=[(0, '0分'), (1, '5分')], default=False, verbose_name='*经营现金流量负债比（5）')),
                ('i16', models.BooleanField(choices=[(0, '0分'), (1, '5分')], default=False, verbose_name='*流动比率（5）')),
                ('i17', models.BooleanField(choices=[(0, '0分'), (1, '5分')], default=False, verbose_name='*利息保障倍数（5）')),
                ('i18', models.BooleanField(choices=[(0, '0分'), (1, '10分')], default=False, verbose_name='研发费用收入比例(10)')),
                ('create_date', models.DateTimeField(auto_now=True, null=True, verbose_name='生成时间')),
                ('companyInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyInfo', verbose_name='企业')),
            ],
            options={
                'verbose_name': '投资类金融报告',
                'verbose_name_plural': '投资类金融报告',
            },
        ),
    ]
