# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-11 02:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(blank=True, choices=[(1, '投资'), (2, '银行')], null=True, verbose_name='机构类型')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='机构名称')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='机构手机')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
