# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-11 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': '机构', 'verbose_name_plural': '机构'},
        ),
    ]
